spec/pg/connection_spec.cr, spec/pg/decoder_spec.cr, src/pg/connection.cr, src/pg/decoder.cr, src/pg/libpq.cr, src/pg/result.cr
=> Support passing and reading binary data

spec/pg/connection_spec.cr, src/pg/connection.cr
Add spec for escape_literal.
Fix compiler/syntax error.
=> Add escape_literal overload for binary data.

spec/pg/connection_spec.cr, src/pg/connection.cr
I'm sorry. I mistook and close PR.
https://github.com/will/crystal-pg/pull/25
Please discuss one more time about `Hash(YAML::Type, YAML::Type)` and `Hash(String, YAML:: Type)`.
Thanks.
=> Add connection with using Hash values.

src/pq/connection.cr, src/pq/param.cr
Still openssl spec failures though
=> (incomplete) compile on 0.18.0

shard.yml, src/pg/connection.cr
=> Feature/crystal 0.20.3

shard.yml, spec/spec_helper.cr, src/pg.cr, src/pg/connection.cr, src/pg/driver.cr
* Use `DB.connect` in ListenConnection to avoid creating a connection pool.
* Updates to use db 0.4.0.
=> Update to crystal-db 0.4.0

shard.yml
@see https://github.com/crystal-lang/crystal-db/blob/master/CHANGELOG.md
=> crystal-db has been updated

spec/pg/numeric_spec.cr
Ref: https://github.com/crystal-lang/crystal/pull/7297
=> Remove nested it in numeric_spec.cr

spec/pg/encoder_spec.cr, spec/pq/param_spec.cr, src/pq/param.cr
=> Fix encoding string arrays with special characters

spec/pg/connection_spec.cr, src/pg.cr, src/pg/connection.cr
=> Add `Enumerable` channels overload for `PG.connect_listen`

shard.yml, src/pg/connection.cr, src/pg/driver.cr, src/pg/result_set.cr
Depends on https://github.com/crystal-lang/crystal-db/pull/108 (and its release)
=> Annotate return types of abstract methods

spec/pg/encoder_spec.cr, src/pq/param.cr
=> Fix encoding format of time with no-zero offset

shard.yml, spec/pg/encoder_spec.cr
There is a new release of crystal-db with some breaking changes.
Ref: https://github.com/crystal-lang/crystal-db/pull/110
=> Update to crystal-db ~> 0.7.0

CONTRIBUTING, CONTRIBUTING.md
After visiting the repo, I wanted to see if I could run the test suite
and could not find the directions.
Hopefully these are simple and clear enough for most people to get
started.
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
=> docs: add dev setup documentation

src/pq/connection.cr, src/pq/param.cr
=> Upgrade support to Crystal 0.35

shard.yml, src/pg/statement.cr, src/pq/connection.cr, src/pq/param.cr
Depends on https://github.com/crystal-lang/crystal-db/pull/134
=> Update crystal-db for logging support

spec/pg/decoders/array_decoder_spec.cr, src/pg/decoders/array_decoder.cr
=> Add UUID to array decorders.

.github/workflows/config.yml
Still looks like packages aren't on wherever CI gets them from yet, so redoing this and leaving it open
=> Start testing pg15

.github/workflows/config.yml
Got some warnings that the v2 one would stop working
=> Update github actions checkout step

src/pq/connection.cr
=> Replace references of Saml to Sasl
