will/crystal-pg

spec/pg/connection_spec.cr, spec/pg/result_spec.cr, spec/spec_helper.cr, src/pg.cr
The `extra_float_digits` setting must be at least `2` when reading 64-bit floats (and `3` for 32-bit floats) from Postgres to ensure that fidelity is preserved for all values (i.e., client and server are talking about the exact same bits).
As the Postgres community likes to point out, this is only meaningful for when both client and server have IEEE754 floating point implementations, but come on...
This is not ready to merge because of a spec failure, but I'm not sure if this is due to some issue in my patch, crystal-pg, or in crystal itself. The [semantically-equivalent test passes in pq](https://github.com/lib/pq/blob/master/conn_test.go#L845-L862). Any ideas?
=> Default extra_float_digits to 3 to preserve IEEE754 float fidelity

spec/pg/connection_spec.cr, src/pg/connection.cr
This simple method allow to run multiple requests at once.
Useful when loading SQL files (migrations)
=> exec_all method to allow multiple requests

spec/pg/result_spec.cr, src/pg/result.cr
Hi, I tried to use:
```crystal
DB.exec({String, String, Bool, Int32},
"select 'a' as foo, 'b' as bar, true as baz, 10 as uhh
union all
select '', 'c', false, 20").to_hash
```
Gives the next error:
```
instantiating 'PG::Result({Int32:Class, String:Class, String:Class, String:Class})#to_hash()'
connect {|db| user = db.exec({Int32, String, String, String}, 
^~~~~~~
in ./libs/pg/pg/result.cr:37: no overload matches 'Hash(K, V)::zip' with types Array(String), {Int32, String, String, String}
Overloads are:
- Hash(K, V)::zip(ary1 : Array(K), ary2 : Array(V))
Hash.zip(field_names, row)
```
This PR solves the previous problem.
=> Allows typed querying when to_hash method is used in query results

.travis.yml
https://travis-ci.org/will/will/crystal-pg/builds/86702573
Looks like I missed something on the travis nightly support. I should have spun up the docker whatever things to test locally but I was pretty sure it would work. Hubris.
=> try out fancy crystal nightly on travis

spec/pg/result_spec.cr, src/core_ext/class.cr, src/pg.cr, src/pg/connection.cr, src/pg/result.cr
This allows to map a PG result to a struct or class, avoiding temporary memory structures (ie. Tuples and Hashes). I use this pattern extensively and would love to see it merged.
To achieve this, I keep a reference to the LibPQ::PGResult structure and delay the resolution of the rows and fields gatherer to be on demand. Actually only the rows have to, since fields is used by the iterator.
=> Iterate rows and fields from results

src/core_ext/scheduler.cr, src/pg/connection.cr, src/pg/libpq.cr
I noticed that PG::Connection#exec was blocking the event loop. I followed http://www.postgresql.org/docs/9.3/static/libpq-async.html page, hacked a few things and... it actually worked.
Here is an example, which prints `done (i)` on the screen every second when the connection is evented. instead of waiting for `i` seconds between each prints:
```crystal
require "pg"
DB_URL = ENV["DATABASE_URL"]? || "postgres:///"
5.times do |i|
spawn do
db = PG.connect(DB_URL)
db.exec("SELECT pg_sleep(#{i});")
puts "done (#{i})"
end
end
sleep
```
I pushed the pull request for feedback. It seems to be working fine, specs are passing, and the above test too. I verified we can execute multiple queries from the same coroutine (one after another) but executing queries to a single connection from different …
=> Event loop

src/pq/connection.cr
Adds a missing `true`. It works without it too, but it's just coincidence. `handle_notification` returns `Void`, and right now it's considered truthy. I plan to make some changes to `Void` and without this fix this code breaks.
=> Add missing `true` in PQ::Connection#handle_async_frames

README.md, spec/pg/decoder_spec.cr, src/pg/decoder.cr, src/pg/geo.cr
I decided to add types for things whose representation if the same, for example Box and LIneSegment, mostly because they represent different things, and one could imagine adding different methods to them. The same applies to Line and Circle. For Path I couldn't use `record` because I needed a query method (`closed?`), I'll think how we can make `record` do that automatically.
=> Add property Geo types. Implements #48

src/pg/connection.cr
From https://github.com/crystal-lang/crystal-db/pull/25 (currently in master but not released) a connection will create prepared and non prepared statements. This is required for uniform transactions api.
It seems crystal-pg has only implemented non prepared statements so the quick solution is to reuse them when ever a prepared statement is expected.
Prepared statements have special treatment since they need the be released as opposed to non prepared ones.
I would vouch for a proper prepared statement in postgres, but I am not sure you will agree.
=> update to db unprepared statements

shard.yml, spec/pg/driver_spec.cr
crystal-db 0.3.0 was just released.
* fixes master using crystal-db 0.3.0
* fixes https://github.com/will/crystal-pg/pull/66#issuecomment-266916971
* add specs for transaction and nested transactions
cc: @samueleaton
=> Use db 0.3.0

shard.yml, spec/pg/connection_spec.cr, spec/pq/authentication_methods_spec.cr, src/pg/connection.cr, src/pg/result_set.cr, src/pg/statement.cr
This PR enables the connection pooling from crystal-db to work with crystal-pg.
In order for the connection pool to work `DB::ConnectionLost` and `DB::ConnectionRefused` need to be raised when executing commands or establishing connections.
This also requires to crystal-db ~> ~~0.3.1~~ 0.3.2 
the fix for `pq/authentication_methods_spec.cr` could be different, those specs uses `/pg/*` so now the exception to expect need to be `DB::ConnectionLost` and `DB::ConnectionRefused`.
cc: @raydf
=> Enable connection pool

spec/pg/escape_helper_spec.cr, src/pq/connection.cr
1. `assert` is now `it`
2. `Crypto::MD5` is now `Digest::MD5`
=> Support for Crystal 0.21.0

spec/pg/connection_spec.cr
While working on crystal-lang/crystal-db#35 I notice that the following spec will break.
This PR fixes things beforehand and it also make sense today.
~~I will send a related PR to discuss listen/notify across other connections.~~ see #79
The former spec worked only because the same connection was been used for listen & notify.
=> ensure listen/notify spec works in same connection

.travis.yml, spec/pg/decoder_spec.cr, spec/pg/encoder_spec.cr
+ I've noticed that `crystal-pg` was using `postgresql` **9.4** libraries on all tests suites (even when specified `9.1`), so I change to **sudo-based**
+ I use socket connections instead of IP based, due to an travis error (I think) => reported
https://github.com/travis-ci/travis-ci/issues/7449
+ I add test env using `postgresql `**9.5** / **9.6**
PS : 
Travis feature
~~~yaml
addons
~~~
is deprecated https://docs.travis-ci.com/user/addons/
=> Use vm based ci

README.md
Since `trusty` usage on `travis` we use [PostgreSQL](https://www.postgresql.org) :
+ 9.2
+ 9.3
+ 9.4
+ 9.5
+ 9.6
=> pg version has been update on ci

spec/pg/driver_spec.cr, src/pg/result_set.cr
PG would hang indefinitely if an exception was raised, but not handled.  This is due to `@end` not being set to true when this occurs so while attempting to process the result_set it gets caught in an infinite loop.
Issues related can be seen at
https://github.com/will/crystal-pg/issues/98
https://github.com/crystal-lang/crystal-db/issues/46
https://github.com/Crecto/crecto/issues/76
=> Patch to fix hanging on unhandled exceptions

src/pg/result_set.cr
crystal-pg would hang indefinitely or throw an error when there were unread null values.
The skip function didn't skip bytes when the column byte size was 1 but it should be -1 which is when it's null.
Fixes
https://github.com/will/crystal-pg/issues/102
https://github.com/crystal-lang/crystal-db/issues/59
=> Fix skipping null values

shard.yml
Fixes #122 .
@will a new crystal-db was released for 0.24, no changes in the api.
I realized later that that bump was not really need. I'll try to be more careful next time.
=> Update to use crystal-db ~> 0.5.0

.travis.yml
Somehow travis wasn't being used to run specs anymore.
=> enable travis spec

src/pq/connection.cr
Fixes connections with encoding set as lowercase `utf8` as opposed to `UTF8` that still have compatible encoding.
Notably, this prevents an error being raised when using [PgBouncer](https://pgbouncer.github.io/) in Heroku for [client-side connection pooling](https://devcenter.heroku.com/articles/on-dyno-postgres-connection-pooling).
=> Check connection client encoding is UTF8, case-insensitive

.travis/setup.sh, spec/pq/authentication_methods_spec.cr, spec/pq/conninfo_spec.cr, src/pq/connection.cr, src/pq/conninfo.cr
Allow clientcert authentication using query parameters that resemble the parameter key words (`sslcert`, `sslkey`, `sslrootcert`): https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS.
=> Enable clientcert authentication

src/pq/conninfo.cr
* URI#host is no longer nilable, checking for blank is required to return the right default host
* Add require to allow running spec/pq/conninfo_spec.cr in isolation
The change is backward compatible with Crystal 0.20 (and crystal-db 0.5 requires Crystal 0.24)
=> Upgrade to Crystal 0.28.0

src/pg/connection.cr
* The `PQ::Connection#close` might raise. `#do_close` should never raise
* A call to super to clean up resources was missing
=> Surround call PQ::Connection#close with rescue

src/pg/statement.cr
If a closed connection is used in a query it will immediately exit with `IO::Error: Closed stream`. Since currently only `EOFError`s are rescued, a closed connection will be re-used in subsequent queries and will always fail.
Please let me know if this is not the correct fix for this or if there is another reason for using `IO::EOFError` and not the parent `IO::Error`.
=> Fix IOError on closed connection

README.md, spec/pg/decoders/array_decoder_spec.cr, spec/pg/numeric_spec.cr, src/pg/decoder.cr, src/pg/decoders/array_decoder.cr, src/pg/numeric.cr, src/pg/result_set.cr
Fixes #105
Fixes #172
There are several commits here:
1. If an exception happened while trying to decode an array we should have skipped the remaining bytes for that column. We already do that when reading something that's not an array, it was missing for an array. This was the reason for the hang up.
2. Let `Numeric#inspect` use `Numeric#to_s`, which all number types in Crystal do. Probably doesn't belong here but it made debugging things easier.
3. Previously you could decode an array of numeric as an array of float (you can print the value in #105 and you'll see garbage). So now we check that the correct array type is read.
4. A refactor so that each type maps univocally to a decoder. For example now there's a single `TimeDecoder` that deals with postgres dates and times. This commit …
=> Some array fixes

spec/pg/decoder_spec.cr, src/pg/decoder.cr
Fixes #148 
Just doing `read` could end up not filling the passed slice and so it ended up with garbage bytes.
=> Use Slice#ready_fully in UUID decoder

spec/pg/encoder_spec.cr, src/pq/param.cr
Fixes #140
I was able to reproduce the issue and fix suggested by @aisrael seems to work well.
I could extract the format string to a constant but I didn't know how to name it (maybe like this it's fine).
=> Correctly encode timestamp values to consider microseconds

spec/pg/decoder_spec.cr, src/pg/decoder.cr
Fixes #186
I don't know why the old code was doing that, maybe there's a reason? In any case all specs seem to pass with this change. I also tried (but didn't include in the specs) putting `Int64::MAX` and `Int64::MIN` and they work fine.
=> Read Int64 directly instead of converting from UInt64

.circleci/config.yml
I intended to also drop 9.4 but it looks like the postgres project supports it until some time between dec 18, 2019 and feb 13, 2020, so might as well keep the builds on until then.
=> add postgres 12 CI builds

shard.yml
There is a new release of crystal-db.
It would be ideal to release a crystal-pg 0.20.0 IMO
=> Update to crystal-db ~> 0.8.0

src/pg/escape_helper.cr, src/pq/connection.cr, src/pq/conninfo.cr, src/pq/frame.cr, src/pq/notice.cr
This PR updates for compatibility with newly release Crystal 0.34.0 addressing the breaking changes from crystal-lang/crystal#8885 and crystal-lang/crystal#8424.
=> Crystal 0.34.0

shard.yml, src/pq/connection.cr
And keep support for older than Crystal 0.34.0 https://github.com/will/crystal-pg/pull/203#issuecomment-610082732. 
Some tools state that they work with also previous versions of Crystal.
Since we are doing some heavy cleanup for 1.0, soon we can remove them. I usually encourage at least previous + latest support to simplify the migration of apps codebases.
If a v0.21.0 can be released as is it would be great. Let me know if I can give you a hand with something else @will .
=> Update to crystal-db ~> 0.9.0

spec/pg/decoder_spec.cr, src/pg/decoder.cr
Crystal: 0.35.1
Postgres: 12.3
One of my apps uses UUIDs for all identifiers, but this requires me to put a `@[DB::Field(converter: UUIDConverter)]` annotation on every single identifier and foreign key in my app models:
```crystal
struct Comment
include DB::Serializable
@[DB::Field(converter: UUIDConverter)]
getter id : UUID
@[DB::Field(converter: UUIDConverter)]
getter commentable_id : UUID
@[DB::Field(converter: UUIDConverter)]
getter author_id : UUID
end
```
So I thought it'd be really nice if I didn't have to add that annotation every time since Postgres has a UUID data type. And then I saw [this comment](https://github.com/will/crystal-pg/pull/130#issuecomment-359862351) from @RX14:
> However, returning UUIDs as the new `UUID` struct would be something to discuss
So I wanted to at …
=> Allow decoding directly to UUID struct

.circleci/config.yml
It's annoying when CI fails early because of a format error and doesn't run specs.
Also formatter is independent of postgres version matrix.
=> [CI] Run check_format as separate job

.circleci/pg_hba.conf, spec/pq/authentication_methods_spec.cr, spec/pq/conninfo_spec.cr, src/pq/connection.cr, src/pq/conninfo.cr
This adds a `auth_methods` config setting which allows to configure which auth methods the client should accept.
The settings value is a list of comma separated values. The default is `scram-sha-256,md5`. `cleartext` needs to be explicitly enabled.
Is there any place where documentation can be added?
I didn't do anything about `OK` authentication frame. A safe default should also fail if the server just passes you through without a credential check.
But this is more complicated because it is fine with SSL client certificate for example.
So it needs more work. For now I'm just posting this patch.
Superseeds #218
cf crystal-lang/crystal-db#141
=> Add config setting auth_methods

spec/pg/driver_spec.cr, src/pg/result_set.cr
Fixes #43
In order to support the citext extension in Avram, we need to be able to treat the column as a String. Two solutions were laid out in the connected issue:
- A: Calling `rs.read(String)` on a string-like column (citext, enum or similar), it should return a String.
- B: Calling `rs.read` on a string-like column, it should probably also return a String.
B was considered the more "complete solution" but also the more complicated. Since it's been 4 years since the issue was opened and over a year since the potential solutions were laid out, I went with the more immediate option A. If the read type is `Slice(UInt8)`, which is the type of a citext column, and `#read` was called with a type of `String`, then convert it to String. This helps with citext interop and I'm sure it helps with …
=> Read Slice(UInt8) as String if given as type

shard.yml, spec/spec_helper.cr
This PR makes the spec build on Crystal 0.36 without warnings.
The changes are backward compatibly with 0.35.
Another optional change is to declare this shard compatible with 1.0.0-x which should be almost 0.36. Is not mandatory and --ignore-crystal-version can be used otherwise.
=> Update for Crystal 0.36 compatibility

src/pg/result_set.cr
_TL;DR: Reduced CPU consumption by about 73%, but still needs some polish_
I've been benchmarking Crystal vs Rust/Go for some reasonably realistic workloads. A while back I compared [communicating with Redis](https://dev.to/jgaskins/performance-comparison-rust-vs-crystal-with-redis-1a17) (because it's simple) between Rust and Crystal — Crystal beat Rust by a factor of 2-3x.
This week I ran a similar set of benchmarks for Postgres, using [Diesel](https://diesel.rs) for Rust and [Interro](https://github.com/jgaskins/interro) for Crystal, with varying horse-sized-duck and duck-sized-horse queries, and Rust beat Crystal by almost the same amount, so I started looking and found that [`PG::ResultSet#read` calls `safe_read`](https://github.com/will/crystal-pg/blob/cafe039cfd6340a271e81603943bb197 …
=> Reuse IO::Sized instances in ResultSet

CHANGELOG, spec/pg/decoder_spec.cr, spec/pg/driver_spec.cr, spec/spec_helper.cr, src/pg/decoder.cr, src/pg/result_set.cr
Fixes #125 
Currently, if you have a json column and read it with this library, it is automatically turned into a `JSON::Any`. It makes sense when you don't care about the structure, but there's two problems with doing that:
1. `JSON::Any` is immutable so that values cannot be changed and then saved back to the database
2. You cannot convert a `JSON::Any` into a `JSON::Serializable`
This PR changes the default deserialization of json columns from `JSON::Any` to `JSON::PullParser`. The benefit we get from this is that it can easily be converted into a `JSON::Any` or a `JSON::Serializable`. It is still not mutable but it's easier to get to a mutable setting:
```crystal
properties = result_set.read(JSON::PullParser)
mutable_properties = Hash(String, String).new(properties)
```
I added a …
=> Json columns are read as JSON::PullParser instead of JSON::Any

CHANGELOG, src/pq/connection.cr
CVE-2021-23222 (announced today 2021-11-11) doesn't directly affect this driver as it does
libpq-based drivers, since this driver only reads the single byte when
checking for TLS support on the server instead of eagerly reading as
much data as possible.
However, should this attack be attempted on this driver, it shows up as
the TLS handshake failing. Instead, check for this attack and raise an
error with the evidence, so users can know that there is a
man-in-the-middle up to no good.
=> Add defense-in-depth for CVE-2021-23222

spec/pq/conninfo_spec.cr, src/pq/conninfo.cr
When connecting to a postgres instance via socket, the hostname parsed
by URI.parse is left empty, while a query string with the host is added
If the hostname is left blank, fallback to the host provided by the
query string
Resolves #227
=> Fix socket connections via url connection string

src/pq/conninfo.cr
This is a performance improvement. `partition` doesn't allocate an array.
As a side effect, this also gets rid of rescuing `IndexError` (cf https://github.com/crystal-lang/crystal/issues/11565#issuecomment-1003040007).
=> Refactor `String#split` to `String#partition`

CHANGELOG, examples/listen_notify.cr, src/pg.cr, src/pg/connection.cr
I think this addresses the things brought up in #195 by having connect_listen be optionally blocking and not add any breaking changes to this area.
=> Connect listen changes

spec/db_spec.cr
crystal-db 0.4.1 includes some common specs across drivers. This is a minimum usage of those.
It could include other datatypes that crystal-pg supports. It apart from testing literals in a similar fashion that in decoder_spec.cr, this shared specs make some heavy usage of many overloads to ensure all db api works with all sample value data types.
Unfortunately for the specs to pass we need `$ crystal spec --no-debug` until the crystal version is released. That is the sole reason why the `[WIP]` on my side.
FYI Inside the `DB::DriverSpecs(DB::Any).run` you can: 
```crystal
DB::DriverSpecs(DB::Any).run
it "..." do |db|
end
end
=> Use db shared specs

.circleci/config.yml, .circleci/pg_hba.conf, .circleci/setup.sh, CHANGELOG
It fell out of support from the postgres project itself on Nov 11 2021,
so stop running CI tests for it. https://www.postgresql.org/support/versioning/
The postgres protocol is still unchanged, so it still probably works
fine however.
Now that all supported versions support scram, the CI setup can be
simplified a bit, which is nice.
=> Drop support for postgres 9.6

spec/db_spec.cr
I noticed that the shared specs were making a new connection for every example, which wasn't necessary. Reusing the connection makes the tests to run on my laptop with compile time from an average of 12.275 seconds to 7.877
Nothing is failing now and I think the monkey patch is easy enough to back out should it start causing problems. But maybe there should be an official way to reuse an existing connection for the shared specs?
=> Reuse existing connection for shared specs

src/pq/conninfo.cr
For finding a default username and database name when none is given (eg `postgres:///`), this would previously shell out to running the whoami command. Now it calls libc directly to find the current username.
This was especially slow for the tests before cafe09ed5547 but even now finding this change brings the tests from (avg over 10 runs counting compile time) 7.87 seconds down to 6.94.
=> Stop shelling out to whoami

src/pq/connection.cr
It appears that `crystal-pg` is not compatible with PostgreSQL instances that do not have SSL support, and it seems to be ignoring the `sslmode=disable` parameter. This issue is particularly evident with PostgreSQL databases provisioned in Fly.io since they are accessed over an encrypted internal network, and SSL is not supported in such cases ([ref](https://community.fly.io/t/can-not-connect-to-postgres-sql-ssl-handshake/12093/2)).
To illustrate, I was trying to make this seemingly simple script work:
```crystal
require "db"
require "pg"
DB.connect ENV["DATABASE_URL"] do |cnn|
p cnn
end
```
And I got the following trace:
<details>
<summary>Trace</summary>
```
Unhandled exception:  (DB::ConnectionRefused)
from lib/pg/src/pg/connection.cr:16:9 in 'initialize'
from …
```
=> Ensure sslmode=disable is respected

spec/pq/conninfo_spec.cr, src/pq/conninfo.cr
This change makes the driver find the actual socket file and is consistent with how libpq appends .s.PGSQL.5432 to the value of the env var when it's a path:
❯ mkdir -p /tmp/foo && PGHOST=/tmp/foo psql
psql: error: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/foo/.s.PGSQL.5432"?
When the value is a domain the behavior doesn't change
=> bugfix: treat PGHOST env var as directory when it's a path

.gitignore, spec/pg/connection_spec.cr, spec/pq/conninfo_spec.cr, src/pq/connection.cr, src/pq/conninfo.cr
Add support for `application_name` because not everything can be called crystal.
=> Add support for application_name

src/pg/result_set.cr
When requiring multiple database drivers (e.g. `mysql` or `sqlite3` in addition to `pg`), compilation will fail:
```
In lib/pg/src/pg/result_set.cr:18:51
18 | @sized_io = Buffer.new(conn.soc, 1, statement.connection)
^---------
Error: expected argument #3 to 'PG::ResultSet::Buffer.new' to be PG::Connection, not DB::Connection
```
As long as we don't require any other DB driver, `statement.connection` will always be `PG::Connection` as expected, but when requiring multiple drivers, it will be `DB::Connection+`. The solution is to make an explicit cast.
=> Fix: statement.connection is a DB::Connection (expected PG::Connection)

shard.yml, shards.nix, spec/pg/driver_spec.cr, spec/pq/authentication_methods_spec.cr, src/pg/result_set.cr, src/pg/statement.cr
`crystal-db` v0.13.0 was [just released](https://github.com/crystal-lang/crystal-db/releases/tag/v0.13.0) with some important changes:
- Add exception cause support to `PoolResourceLost` and `ConnectionLost` constructors
- Fix inflight counter on `ConnectionRefused`
- Fix `max_idle_pool_size` race condition
=> Use DB v0.13

src/pq/connection.cr
👋 At Neon, we use SNI to know which database endpoint is being requested to connect to. Our fallback options are using `options` which this library also doesn't support, or using cleartext passwords and encoding the database endpoint into the password. See https://neon.tech/docs/connect/connection-errors#the-endpoint-id-is-not-specified
Reading https://forum.crystal-lang.org/t/specifying-the-sni-hostname-for-an-openssl-context/3872 it seems like enabling SNI wasn't too challenging. Testing locally it does seem to work.
=> fix: enable SNI

CHANGELOG, flake.lock, flake.nix
PG11 went out of support last November, so remove it from the tests November 9, 2023
=> remove pg11 and update deps

spec/pg/encoder_spec.cr, src/pq/param.cr
Resolves #272.
I opted to encode the `PG::Interval` using the textual representation of a PG interval type, primarily to just have the most accuracy.
=> Support encoding `PG::Interval` params

spec/pg/encoder_spec.cr, src/pq/param.cr
_Decoding_ enum values is [already supported in DB](https://github.com/crystal-lang/crystal-db/blob/532ae075bd810cfd0032b74189ec01fcfba2f355/src/db/result_set.cr#L156-L175), but _encoding_ still requires explicitly specifying `enum.value` in query args. This PR uses the `value` property implicitly.
An argument could be made that it would be easier to understand the query if we use the string representations of the Crystal `enum`s instead, but I'm proposing the numeric values for three reasons:
1. An `int4` values takes up less space than a `text`
2. Storing the text representation makes `@[Flags]` enums painful to parse, but the integer representation makes them trivial
3. The `enum` _is_ an `Int32`
Example:
```crystal
require "pg"
struct User
include DB::Serializable
getter id : UUID …
```
=> Encode Crystal enum args as integers

spec/pq/param_spec.cr, src/pq/param.cr
Ran into #267 tonight trying to bulk-insert MessagePack-encoded data (via `unnest`) and can confirm that it's `Array(Bytes)` that it's choking on. Since all arrays are text-encoded, we need to ensure text encoding for `Bytes` can handle binary data.
I tried special-casing `Array(Bytes)` all the way down, but not only does that require a lot more understanding of the binary encoding format than I currently have, it would've been an incomplete solution that only handles linear `bytea` arrays. Anyone using nested arrays would run into the same problem. So I decided against that.
I don't like that this solution increases the payload size over the wire by encoding every byte as 2 hexadecimal characters. Arrays of strings are implemented in terms of this method, so this impacts `text[]` …
=> Handle `Array(Bytes)` encoding for query params containing non-Unicode text

CHANGELOG, src/pq/conninfo.cr
partially address #291
@jwoertink does this make it not crash at least? I don't have a windows install to test on myself
=> windows: avoid breaking Libc.getuid call

spec/db_spec.cr, spec/pq/connection_spec.cr, spec/pq/pgpass_spec.cr, spec/spec_helper.cr, src/pg/result_set.cr, src/pq/connection.cr, src/pq/query.cr
Crystal nightly has a couple new formatter rules enabled: https://github.com/crystal-lang/crystal/pull/14718
The changes are backwards-compatible, so Crystal 1.14.0 won't complain about the new format.
=> `crystal tool format` with Crystal 1.15.0-dev

src/pq/connection.cr
TLDR: ~2x to ~10x+  speedup when sending large query parameters, simply by doing `soc.write(p.slice)` instead of `p.slice.each { |byte| write_byte byte }`. 🐰 
-----
| Parameter Size | Speedup (type=Bytes) | Speedup (type=String) |
| --- | --- | --- |
| 16 MiB | 2.66x | 1.97x |
| 4 MiB | 14.34x | 2.74x |
| 1 MiB | 11.86x | 2.94x |
| 128 kiB | 6.68x | 2.50x |
| 8 kiB | 1.68x | 1.56x |
**BEFORE THIS PR**
```
0 Bytes   40.95k ( 24.42µs) (± 2.65%)  592B/op
1 Bytes   41.74k ( 23.96µs) (± 1.75%)  592B/op
16 Bytes   41.44k ( 24.13µs) (± 1.60%)  592B/op
256 Bytes   37.74k ( 26.50µs) (± 7.59%)  592B/op
1024 Bytes   35.04k ( 28.54µs) (± 5.90%)  592B/op
8192 Bytes   19.44k ( 51.44µs) (± 0.50%)  592B/op
131072 Bytes    2.39k (419.15µs) (± 0.44%)  595B/op
1048576 Bytes  310.64  (  3.22ms) (± 0.46%) …
```
=> `PQ::Connection#send_bind_message`: write entire slice to socket at once
